chore: revise config

diff --git a/linux/roles/common/templates/zsh/zshfunc.j2 b/linux/roles/common/templates/zsh/zshfunc.j2
--- a/linux/roles/common/templates/zsh/zshfunc.j2
+++ b/linux/roles/common/templates/zsh/zshfunc.j2
@@ -60,8 +60,8 @@ path-rm() {
 # @param 2...n (alias): Will be validated and exported, if valid...
 #
 alias-add() {
-  readonly required_command=${1:?"The 'required_command' must be specified."}
-  : ${2:?"At least 1 alias must be specified."}
+  readonly required_command=${1:?"The 'required_command' may be specified."}
+  : ${2:?"At least 1 alias may be specified."}
 
   shift
 
@@ -90,63 +90,88 @@ alias sudo='sudo '
 
 # alias update_zsh="source ~/.zshrc"
 
+alias d='dirs -v | head -10'    # To use: cd ~<number> -or- enter <number> directly
+
 alias ls='ls -G'
+{% if ansible_facts.os_family == 'Darwin' %}
 alias l='ls -lah --color=auto'
 alias ll='ls -lh --color=auto'
 
+alias-add gsed decolorize='gsed -r "s/\\x1B\\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"'
+{% else %}
+alias l='ls -lah'
+alias ll='ls -lh'
+
 alias decolorize='sed -r "s/\\x1B\\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"'
+{% endif %}
 
 alias stat='stat -x'
 
 alias dusage='du -h -d1'
 
-# alias delete_ds="find . -type f -name '.DS_Store' -delete"
 
 alias inet-pg="echo 'Pinging Google' && ping google.com"
 alias inet-public_ip="curl -4 icanhazip.com && curl -6 icanhazip.com; echo"
 
-# Use max # of threads
-alias xz='xz -T 0'
 
 
 
 # --- Installed tools  ---
-{% if 'il_workstations' in group_names %}
+{% if 'il_workstations' in group_names    or ansible_facts.os_family == 'Darwin' %}
 alias-add yt-dlp   vid-download="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"   vid-download_audio="yt-dlp -f 'bestaudio[ext=m4a]'"
 alias-add vid-download vid-download-channel="vid-download  -o '%(channel)s - %(title)s-%(id)s.%(ext)s'"
 alias-add vid-download vid-download-workaround_fname="vid-download  -o '%(title).200s  [%(id)s].%(ext)s'"         # Workaround for: https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195
 {% endif %}
 
+{% if ansible_facts.os_family == 'Darwin' %}
+# - Orginal alias-name: update_hosts
+# Note: npm install -g --prefix /usr/local hblock
+alias-add hblock hblock-up="sudo hblock -H /etc/hblock.d/header -A /etc/hblock.d/whitelist.list -D /etc/hblock.d/blacklist.list"
+{% endif %}
+
 # - Replace existing commands -
 alias-add pigz gzip='pigz' gunzip='unpigz'
 alias-add pbzip2 bzip2='pbzip2' # bunzip2='pbunzip2' bzcat='pbzcat'
+{% if ansible_facts.os_family == 'Darwin' %}
+alias-add colordiff diff='colordiff'
 
-{% if 'dev_workstations' in group_names or 'dev_servers' in group_names %}
+# Use max # of threads
+alias xz='xz -T 0'
+{% endif %}
+
+{% if 'dev_workstations' in group_names or 'dev_servers' in group_names    or ansible_facts.os_family == 'Darwin'%}
 alias pmake='time nice make -j$(nproc) --load-average=$(nproc)'               # Taken from: https://stackoverflow.com/a/4778475
 {% endif %}
 
 
 
 # ---------------------- ------ Environment variables  (which SHOULD be in '.zshenv') ------ ----------------------
-{% if 'dev_workstations' in group_names or 'dev_servers' in group_names %}
+{% if ansible_facts.os_family == 'Darwin' %}
+export LSCOLORS=ExFxCxDxBxegedabagacad  # Default (only brighter)
+# export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx  # Black background
+# export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd  # Linux terminal
+{% else %}
+{%   if 'dev_workstations' in group_names or 'dev_servers' in group_names %}
 #export MAKEFLAGS="-j$(nproc)"
+{%   endif %}
+# ...
 {% endif %}
 
 
-
-# --- GNU/Linux specific ---
+# =========================== Aliases ===========================
+{%   if ansible_facts.os_family != 'Darwin' %}
 alias journal-clear='sudo journalctl --vacuum-time=2d' # --vacuum-size=500M
 
-{% if 'rpis' in group_names %}
+{%   if 'rpis' in group_names %}
 # --- RPi specific ---
 alias temp='vcgencmd measure_temp'
-{% endif %}
+{%   endif %}
 
-{% if 'dev_workstations' in group_names or 'dev_servers' in group_names %}
+{%   if 'dev_workstations' in group_names or 'dev_servers' in group_names %}
 alias-add objdump obj="objdump -M intel -C --visualize-jumps -d "               # Note: Used 2 be fct. w/ (now removed) suffix: `$@ | nvim -`
-{% endif %}
+{%   endif %}
 
-{% if ansible_facts.os_family == 'Debian' %}
+{%   if ansible_facts.os_family == 'Debian' %}
 # - apt-get aliases
 alias agi='sudo apt-get install' #<packages>
 alias agu='sudo apt-get update'
@@ -158,6 +183,7 @@ alias agc='sudo apt-get clean'
 alias agac='sudo apt-get autoclean'
 
 alias agud='agu && agd'
+{%   endif %}
 {% endif %}
 
 
@@ -227,3 +253,132 @@ if command -v ssh-keygen > /dev/null; then
   }
 
 fi
+
+{% if ansible_facts.os_family == 'Darwin' %}
+# - ffmpeg stuff -
+if command -v ffmpeg > /dev/null; then
+
+  mp4-merge_video_audio_stream () {
+    local video_stream=${1:?"The 'video_stream' may be specified."}
+    local audio_stream=${2:?"The 'audio_stream' may be specified."}
+
+    local output=${3:=output.mp4}
+
+
+    if [[ -f "$video_stream" && -f "$audio_stream" ]]; then
+      ffmpeg -i "$video_stream" -i "$audio_stream" -c:v copy -c:a copy "$output"
+    else
+      echo "Provided files don't exist!"
+    fi
+  }
+
+
+#  mp4-from_m2ts () {
+#
+#    local input=${1:?"The 'M2TS'-file may be specified."}
+#    local output=${2:=output.mp4}
+#
+#
+#    if [[ -f "$input" ]]; then
+#      ffmpeg -i "$input" -vcodec libx264 -crf 20 -acodec ac3 -vf "yadif" "$output"
+#    else
+#      echo "Provided files don't exist!"
+#    fi
+#  }
+
+  mp3-convert_to () {
+    for f in "$@"; do
+      ffmpeg -i "$f" -acodec libmp3lame -ab 320k "${f%.*}.mp3"    # Replace any file extension w/ .mp3
+    done
+  }
+
+  flac-convert_to_aiff () {
+    for f in "$@"; do
+      ffmpeg -i "$f" -write_id3v2 1 -c:v copy "${f%.*}.aiff"    # Replace any file extension w/ .mp3
+    done
+  }
+
+fi
+
+
+if command -v gifsicle > /dev/null; then
+
+    gif-from_video () {
+      local video_file=${1:?"The 'video_file' may be specified."}
+
+      if [[ -f "$video_file" ]]; then
+        ffmpeg -i "$video_file" -pix_fmt rgb8 -r 10 -f gif - | gifsicle -O3 -o "${video_file}.gif"
+      else
+        echo "Provided file doesn't exist!"
+      fi
+    }
+
+fi
+
+
+# =========================== Aliases  (which SHOULD be in '.zshenv') ===========================
+alias poweroff='/sbin/shutdown -h now'
+alias reboot='/sbin/shutdown -r now'
+
+
+alias-add brew brew-up="brew update && brew upgrade ; brew cleanup ; brew doctor"
+
+
+# alias delete_ds="find . -type f -name '.DS_Store' -delete"
+
+# alias finder-show_hiddenfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
+# alias finder-hide_hiddenfiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
+
+alias dns-flush="sudo dscacheutil -flushcache ; sudo killall -HUP mDNSResponder"
+alias network-disable_packet_filter="sudo pfctl -d"    # Disable Eddie network lock
+
+
+alias backup_poweroff="sudo sh -c 'tmutil startbackup --block && shutdown -h +1'"
+
+alias app-open_all="find /Applications ~/Applications -type d -name '*.app' -prune -exec open -a {} \;"
+
+alias clipbrd-text_2_lower='echo $(pbpaste) | tr "[A-Z]" "[a-z]" | pbcopy'
+alias clipbrd-text_2_upper='echo $(pbpaste) | tr "[a-z]" "[A-Z]" | pbcopy'
+
+
+# - Hackintosh specific -
+if [[ "$(uname -m)" == "x86_64" ]]; then
+  if command -v mountefi > /dev/null; then
+    # alias esp-mount_open='sudo mkdir /Volumes/EFI ; sudo mount -t msdos /dev/disk1s1 /Volumes/EFI && open /Volumes/EFI'
+    alias-add mountefi esp-mount_open='mountefi / && open /Volumes/EFI'
+  fi
+fi
+
+
+
+# =========================== Actual functions ===========================
+dns-reset_server_for_service() {
+  local network_service=${1:?"Network service may be provided."}
+
+  sudo networksetup -setdnsservers $network_service "Empty"
+}
+
+
+if command -v duti > /dev/null; then
+
+  app-set_as_default_for_extension() {
+    local app_path=${1:?"Path to app may be provided."}
+    local file_extension=${2:?"File extension may be specified."}
+
+    local app_cfbid
+    if ! app_cfbid=`mdls -name kMDItemCFBundleIdentifier -r $app_path`; then
+      echo "The provided app-path \"$app_path\" may be invalid."
+      return 1
+    fi
+
+    if `duti -s $app_cfbid $file_extension all`; then
+      echo "OK - Set \"$app_cfbid\" for file extension \"$file_extension\""
+    else
+      echo "FAIL - Couldn't set \"$app_path\" for file extension \"$file_extension\""
+      return 1
+    fi
+
+  }
+
+fi
+{% endif %}
