wip: luks passwordless reboot

diff --git a/roles/common/templates/linux/luks-passwordless_reboot.j2 b/roles/common/templates/linux/luks-passwordless_reboot.j2
--- a/roles/common/templates/linux/luks-passwordless_reboot.j2
+++ b/roles/common/templates/linux/luks-passwordless_reboot.j2
@@ -1,87 +1,122 @@
 #!/usr/bin/env bash
 
-#{{ ansible_managed | comment }}
+{{ ansible_managed | comment }}
 
-# NOTE: VALIDATE -- AFTER REBOOT we want:
-#   - No `/boot/luks_ot_reboot.key`
-#   - No `/etc/systemd/system/luks_ot_reboot.key-cleanup.service`
-#   - No `/var/luks_ot_reboot.key-cleanup`
-#   - No `/boot/luks_ot_reboot.key` entry in `/etc/crypttab`
-#   - Only 1 keyslot in `cryptsetup luksDump "/dev/sda3"`
+{# NOTE:
+     - Ubuntu Server 24.04 LTS 4 Raspberry Pi: initramfs-tools
+       ( SEE: https://discourse.ubuntu.com/t/ubuntu-on-raspberry-pi-summer-25-update/64395/6 )
+     - Ubuntu 25.10 (4 ARM): dracut
+
+    CHECK VIA:
+      - `dpkg -l | grep -E "initramfs-tools|dracut"`
+      - `lsinitramfs /boot/initrd.img-$(uname -r)`
+      - `journalctl -b | grep -Ei 'dracut|initramfs'`
+      - `cat /proc/cmdline`
+#}
+
+{% set OT_KEYFILE = "/boot/firmware/luks_ot_reboot.key" %}{#    !! IMPORTANT: Must be `/boot/firmware` on Ubuntu Server !! #}
+{% set OT_SERVICE_FILE = "luks_ot_reboot.key-cleanup.service" %}
+{% set OT_SERVICE_FILE_DIR = "/etc/systemd/system" %}
+{% set OT_WORKAROUND_SCRIPT_FILE = "/var/luks_ot_reboot.key-cleanup" %}{#    TODO: Should be embedded in the systemd service unit's `ExecStart`, but doesn't work
+… #}
+{% set UUID_DEV_BASED = True %}
 
 set -e
 
 # Check if the script is running as root
 if [ "$EUID" -ne 0 ]; then
-    echo "Must run as root" >&2
+    echo 'Must run as root' >&2
     exit 1
 fi
 
-# Detect cryptroot mapping name (e.g. cryptroot);   `sed` filters btrfs volume
-CRYPT_MAPPER_DEV=$(findmnt -n -o SOURCE /  | sed 's/\[\/@\]//')
+# Detect cryptroot mapping name (e.g. 'cryptroot');   `sed` filters btrfs volume
+crypt_mapper_dev=$(findmnt -n -o SOURCE /  | sed 's/\[\/@\]//')
 
 # Detect underlying encrypted block device
-CRYPT_DEV=$(cryptsetup status "$CRYPT_MAPPER_DEV" | awk '/device:/ {print $2}')
+crypt_dev=$(cryptsetup status "${crypt_mapper_dev}" | awk '/device:/ {print $2}')
 
-if [ -z "$CRYPT_DEV" ]; then
-    echo "Could not detect encrypted root device" >&2
+if [ -z "${crypt_dev}" ]; then
+    echo 'Could not detect encrypted root device' >&2
     exit 1
 fi
 
-# Validate passphrase
-echo -n "Enter (a) passphrase 4 encrypted root device \"$CRYPT_DEV\": "
-read -s passphrase
-echo "$passphrase" | sudo cryptsetup luksOpen --test-passphrase "$CRYPT_DEV"
+crypt_dev_uuid=$(blkid -s UUID -o value "${crypt_dev}")
 
-echo "[+] Installing cleanup service (4 ot (one-time) key)"
-KEYFILE=/boot/firmware/luks_ot_reboot.key            # !! IMPORTANT: Must be `/boot/firmware` on Ubuntu Server !!
-SERVICE_FILE=luks_ot_reboot.key-cleanup.service
-WORKAROUND_SCRIPT_FILE=/var/luks_ot_reboot.key-cleanup  # TODO: Should be embedded in the systemd service unit's `ExecStart`, but doesn't work …
-SERVICE_PATH="/etc/systemd/system"
-cat > "$WORKAROUND_SCRIPT_FILE" << EOF
+# Validate passphrase
+echo -n "Enter (a) passphrase 4 encrypted root device \"${crypt_dev}\": "
+read -s passphrase
+echo '[+] Validating entered passphrase …'
+echo "${passphrase}" | cryptsetup luksOpen --test-passphrase "${crypt_dev}"
+
+# Generate key
+echo '[+] Generating ot key'
+dd if=/dev/urandom of='{{ OT_KEYFILE }}' bs=4096 count=1 status=none
+chmod 0400 '{{ OT_KEYFILE }}'           # NOTE: No effect on FAT FS ?!
+
+# Add cleanup service
+echo '[+] Installing cleanup service (4 ot (one-time) key)'
+cat > '{{ OT_WORKAROUND_SCRIPT_FILE }}' << EOF
 #!/usr/bin/env bash
+
+# NOTE: VALIDATE -- AFTER REBOOT we want:
+#   - No {{ OT_KEYFILE }}
+#   - No {{ OT_SERVICE_FILE_DIR }}/{{ OT_SERVICE_FILE }}
+#   - No {{ OT_WORKAROUND_SCRIPT_FILE }}
+#   - No {{ OT_KEYFILE }} entry in /etc/crypttab
+#   - Only 1 keyslot  (SEE: cryptsetup luksDump "<crypt_dev>")
+
 set -e
-cryptsetup luksRemoveKey --key-file "$KEYFILE" "$CRYPT_DEV"
-sed -i "s|$KEYFILE|none|" /etc/crypttab
-rm -f "$KEYFILE"
-update-initramfs -c -k all                   # update-initramfs -u  ?!?!?!111
-systemctl disable "$SERVICE_FILE"
-rm -f "$SERVICE_PATH/$SERVICE_FILE" "$WORKAROUND_SCRIPT_FILE"
+
+# Remove slot
+cryptsetup luksRemoveKey --key-file '{{ OT_KEYFILE }}' '${crypt_dev}'
+
+# Remove & Delete keyfile
+sed -i 's|{{ OT_KEYFILE }}|none|' /etc/crypttab
+rm -f '{{ OT_KEYFILE }}'
+
+# Rebuild initramfs
+update-initramfs -u -k all
+cp --dereference /boot/initrd.img /boot/firmware/initrd.img   # WORKAROUND: Ubuntu Server 4 Pis initrd /boot/firmware v.s., /boot ?!
+
+# Disable this service & delete it
+systemctl disable '{{ OT_SERVICE_FILE }}'
+rm -f '{{ OT_SERVICE_FILE_DIR }}/{{ OT_SERVICE_FILE }}' '{{ OT_WORKAROUND_SCRIPT_FILE }}'
 EOF
 
-chmod 0744 "$WORKAROUND_SCRIPT_FILE"
+chmod 0744 '{{ OT_WORKAROUND_SCRIPT_FILE }}'
 
-cat > "$SERVICE_PATH/$SERVICE_FILE" << EOF
+cat > '{{ OT_SERVICE_FILE_DIR }}/{{ OT_SERVICE_FILE }}' << EOF
 [Unit]
 Description=Remove one-time LUKS key after boot
 After=multi-user.target
 
 [Service]
 Type=oneshot
-ExecStart=$WORKAROUND_SCRIPT_FILE
+ExecStart='{{ OT_WORKAROUND_SCRIPT_FILE }}'
 
 [Install]
 WantedBy=multi-user.target
 EOF
 
+# Activate cleanup service
 systemctl daemon-reload
-systemctl enable "$SERVICE_FILE"    # but not started yet
+systemctl enable '{{ OT_SERVICE_FILE }}'    # but not started yet
 
-echo "[+] Generating ot key"
-dd if=/dev/urandom of="$KEYFILE" bs=4096 count=1 status=none
-chmod 0400 "$KEYFILE"           # NOTE: No effect on FAT FS
-
-echo "[+] Adding ot key as LUKS keyslot"
-echo "$passphrase" | cryptsetup luksAddKey "$CRYPT_DEV" "$KEYFILE"
+# Install ot key
+echo '[+] Adding ot key as LUKS keyslot'
+echo "${passphrase}" | cryptsetup luksAddKey "${crypt_dev}" '{{ OT_KEYFILE }}'
 
 echo '[+] Setting up auto-unlock (using ot key)'
-# Add keyfile in `/etc/crypttab`
-#UUID=$(blkid -s UUID -o value "$CRYPT_DEV")
-#sed -i "s|^$CRYPT_MAPPER_DEV .*|$CRYPT_MAPPER_DEV UUID=$UUID $KEYFILE luks|" /etc/crypttab
-sed -i "s|$CRYPT_DEV[[:space:]]\+none|$CRYPT_DEV $KEYFILE|" /etc/crypttab
+# Add keyfile in /etc/crypttab
+{% if UUID_DEV_BASED == True %}
+sed -i "s|UUID=${crypt_dev_uuid}[[:space:]]\+none|UUID=${crypt_dev_uuid} {{ OT_KEYFILE }}|" /etc/crypttab
+{% else %}
+sed -i "s|${crypt_dev}[[:space:]]\+none|${crypt_dev} {{ OT_KEYFILE }}|" /etc/crypttab
+{% endif %}
 
-# Rebuild initramfs
-update-initramfs -c -k all                   # update-initramfs -u  ?!?!?!111
+# ( Update initramfs )
+update-initramfs -u -k all
+cp --dereference /boot/initrd.img /boot/firmware/initrd.img   # WORKAROUND: Ubuntu Server 4 Pis initrd /boot/firmware v.s., /boot ?!
 
-echo "[+] Rebooting …"
+echo '[+] Rebooting …'
 reboot
