add shellcheck + revise transmission postscirpt

diff --git a/linux/roles/server/home_server/containers/transmission/templates/script-torrent_done.j2 b/linux/roles/server/home_server/containers/transmission/templates/script-torrent_done.j2
--- a/linux/roles/server/home_server/containers/transmission/templates/script-torrent_done.j2
+++ b/linux/roles/server/home_server/containers/transmission/templates/script-torrent_done.j2
@@ -2,11 +2,11 @@
 
 
 {% if notifications_mail_config is defined %}
-# --- Send mail ---
+# ---  Send mail  ---
 # Create mail msg
-TMP_MAILFILE=`mktemp -t transmission.XXXXXXXXXX`
+TMP_MAILFILE=$(mktemp -t transmission.XXXXXXXXXX)
 
-cat <<- EOF > $TMP_MAILFILE
+cat <<- EOF > "$TMP_MAILFILE"
 From: "Transmission" <{{ notifications_mail_config.smtp_username }}>
 To: "Transmission Admin" <{{ notifications_mail_config.system_admin_mail }}>
 Subject: Finished downloading torrent
@@ -15,15 +15,20 @@ Transmission has finished downloading "{{ '$TR_TORRENT_NAME' if not transmission
 EOF
 
 # Semd mail & cleanup
-curl \
+OUTPUT=$(curl \
   --url "smtps://{{ notifications_mail_config.smtp_host }}:{{ notifications_mail_config.smtp_port }}" --ssl-reqd \
   --user "{{ notifications_mail_config.smtp_username }}:{{ notifications_mail_config.smtp_password }}" \
   --mail-from "{{ notifications_mail_config.smtp_username }}" \
   --mail-rcpt "{{ notifications_mail_config.system_admin_mail }}" \
-  --upload-file $TMP_MAILFILE \
--s > /dev/null
+  --upload-file "$TMP_MAILFILE" \
+  -sS    2>&1 >/dev/null)
 
-rm $TMP_MAILFILE
+if [ $? -ne 0 ]; then
+    echo "Failed at sending mail   ($OUTPUT)"
+    exit 1
+fi
+
+rm "$TMP_MAILFILE"
 {% endif %}
 
 
